type MotionPicture {
    name: String!
    rating: Int,
    movieID: Int,
    genre: String
    releaseDate: String
    watchDate: String
    duration: Int
    watchCount: Int
    prodCompany: String
    photo: String
    notes: String
}

type WatchListItem {
    name: String!
    genre: String,
    movieID: Int,
    priority: Int
    releaseDate: String
    duration: Int
    prodCompany: String
    photo: String,
    overview: String,
    tagline: String,
    voteAverage: Int
}

type Query {
    allMPs: [MotionPicture!]!
    allWLI: [WatchListItem!]!
}