type MotionPicture {
    name: String
    rating: Int
    genre: String
    releaseDate: String
    watchDate: String
    duration: String
    watchCount: Int
    notes: String
}

type Query {
    allMPs: [MotionPicture!]!
}